language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/blink
  - PLATFORMIO_PROJECT_DIR=examples/adc

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
