version: 2
jobs:

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/native-blink

  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/native-blink

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO
          - PIO

